[package]
name = "cgol-tui"
version = "0.2.0"
authors = ["Jeromos Kovacs <iITsnot.me214@proton.me>"]
edition = "2018"
description = "Conway's Game of Life implementation with a TUI"
license = "MIT or Apache-2.0"
documentation = "https://docs.rs/cgol-tui"
repository = "https://github.com/JeromeSchmied/cgol-tui-rs"

[dependencies]
crossterm = "0.27.0"
fastrand = "2.0.1"
ratatui = "0.26.1"
