[package]
name = "conways-game-of-life-cli-rs"
version = "0.1.0"
authors = ["Jeromos Kovacs <iITsnot.me214@proton.me>"]
edition = "2018"

[dependencies]
crossterm = "0.27.0"
fastrand = "2.0.1"
ratatui = "0.26.1"
